move ldap connection out of global flags
msktutil/msktutil pull request #179
Opened 2021-03-02 22:13 UTC by oflebbe

Hi @mproehl , @dkobras . I looked into how the overall code quality can be improved.

One of the misfeatures of msktutil is misusing msktutil_flags for global variables. It makes  unobvious who is in charge of initializing and updating.
Refactored all code to explicitly have it as argument.

While doing that I uncovered a bug: set_password used the ldap connection for determine the password was last set. It was called without initializing ldapConnection first. However the date the password last set was actually not used at all. So the fix is easy by removing the dependency of set_password on a ldapConnection.

Could you please check if I accidentely broke something?

2021-03-06 21:38 UTC, michael-o requested changes

2021-03-06 21:38 UTC, michael-o commented on msktutil.cpp
> +// NULL return are error, unless we are in cleanup mode
The second sentence is weird English...

2021-03-06 21:38 UTC, michael-o commented on msktutil.cpp
> +LDAPConnection *finalize_exec(msktutil_exec *exec, msktutil_flags *flags)
This one confuses me. The method name does not return match to the return value.

2021-03-06 21:38 UTC, michael-o commented on msktutil.cpp
> +        delete ldap;
A few lines later this is set to `NULL` after delete. Why not here?

2021-03-07 09:55 UTC, oflebbe commented
As written previously I should not have opened this PR. @michael-o  Thany you very much for your review, your proposals are right. Feel free to improve it, the branch will be left open, but I will close this PR. One of the reasons is that I cannot test it any more, since I don't have a suitable INFRA around. Thanks

2021-03-07 09:55 UTC, closed without merging